name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/py-plugin-feeds
    permissions:
      id-token: write
      contents: read  # Ensure you have read access to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the exact version you need or use a range like '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  # Added twine to handle the publishing step

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: ${{ secrets.PYPI_USERNAME }}  # Ensure that PYPI_USERNAME is set in your repository secrets
          password: ${{ secrets.PYPI_TOKEN }}  # Ensure that PYPI_TOKEN is set in your repository secrets
